_BASE_: maskformer2_R50_bs16_50ep.yaml
DATASETS:
  TRAIN: ("coco_instance_train_instances65",)
  TEST: ("coco_instance_val_instances65",)
MODEL:
  META_ARCHITECTURE: "MasQTuning"
  SEM_SEG_HEAD:
    NUM_CLASSES: 65
  MASK_FORMER:
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
