_BASE_: maskformer2_R50_bs16_50ep.yaml
DATASETS:
  TRAIN: ("coco_instance_train_novel17",)
  TEST: ("coco_instance_val_novel17",)
MODEL:
  META_ARCHITECTURE: "MasQTuning"
  SEM_SEG_HEAD:
    NUM_CLASSES: 17
  MASK_FORMER:
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.5
      OBJECT_MASK_THRESHOLD: 0.5
