_BASE_: maskformer2_R50_bs16_50ep.yaml
DATASETS:
  TRAIN: ("coco_instance_train_base48",)
  TEST: ("coco_instance_val_base48",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.0001
  STEPS: (327778, 355092)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 50000
TEST:
  EVAL_PERIOD: 200000
MODEL:
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NUM_CLASSES: 1  # class agnostic
  MASK_FORMER:
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    TEST:
      SEMANTIC_ON: False
      INSTANCE_ON: True
      PANOPTIC_ON: False
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
